"use client"
import Link from "next/link"
import { useEffect,useRef,useState } from "react"
import { faq,categories } from "@/lib/faq"
import { LandingNav } from "./landing-nav"
import { RecoveryFooter } from "./recovery-footer"
import { gsap } from "./gsap"
import s from "./recovery-story.module.css"
import f from "./utility-pages.module.css"

export function FAQScreen(){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All'),[open,setOpen]=useState<string[]>([]),root=useRef<HTMLDivElement>(null)
 const filtered=faq.filter(item=>(category==='All'||item.category===category)&&`${item.question} ${item.answer}`.toLowerCase().includes(query.toLowerCase().trim()))
 useEffect(()=>{const sync=()=>{const id=decodeURIComponent(location.hash.slice(1));if(faq.some(x=>x.id===id)){setCategory('All');setQuery('');setOpen([id]);requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView({block:'center'}))}};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[])
 useEffect(()=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion:no-preference)',()=>{gsap.fromTo(root.current!.querySelectorAll('[data-answer]:not([hidden]) p'),{y:8,opacity:0},{y:0,opacity:1,duration:.32,stagger:.05,ease:'power3.out'})});return()=>mm.revert()},[open])
 const toggle=(id:string)=>{const next=open.includes(id)?[]:[id];setOpen(next);history.pushState(null,'',next.length?`#${id}`:location.pathname)}
 const highlight=(text:string)=>{const needle=query.trim();if(!needle)return text;const index=text.toLowerCase().indexOf(needle.toLowerCase());return index<0?text:<>{text.slice(0,index)}<mark>{text.slice(index,index+needle.length)}</mark>{text.slice(index+needle.length)}</>}
 return <><a className={f.skip} href="#faq-content">Skip to questions</a><LandingNav/><main className={s.utility} id="faq-content"><span className={s.eyebrow}>OLUS / FIELD NOTES</span><h1>Questions,<br/>answered.</h1><p className={s.utilityLead}>The model, its assumptions, and the decisions behind a recovery. Start with what you need to know.</p><label className={f.search}><span className="sr-only">Filter questions</span><input type="search" placeholder="Filter questions…" value={query} onChange={e=>setQuery(e.target.value)}/><span aria-live="polite">{filtered.length} of {faq.length}</span></label><div className={f.faqGrid}><nav className={f.categories} aria-label="Question categories">{['All',...categories].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</nav><div ref={root}><div className={f.faqControls}><span className={s.eyebrow}>{category==='All'?'ALL QUESTIONS':category}</span><button onClick={()=>setOpen(filtered.every(x=>open.includes(x.id))?[]:filtered.map(x=>x.id))}>{filtered.length>0&&filtered.every(x=>open.includes(x.id))?'Collapse all':'Expand all'}</button></div>{filtered.length===0&&<p>No questions match “{query}”. <button onClick={()=>{setQuery('');setCategory('All')}}>Clear filters</button></p>}{filtered.map(item=>{const expanded=open.includes(item.id);return <article key={item.id} id={item.id} className={f.faqItem} data-open={expanded}><h2><button id={`${item.id}-header`} aria-expanded={expanded} aria-controls={`${item.id}-answer`} onClick={()=>toggle(item.id)} onKeyDown={e=>{const keys=['ArrowDown','ArrowUp','Home','End'];if(!keys.includes(e.key))return;e.preventDefault();const buttons=Array.from(root.current!.querySelectorAll<HTMLButtonElement>('h2 button')),index=buttons.indexOf(e.currentTarget);buttons[e.key==='Home'?0:e.key==='End'?buttons.length-1:(index+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus()}}><span className={f.index}>{String(faq.indexOf(item)+1).padStart(2,'0')}</span><span>{highlight(item.question)}</span><span className={f.plus} aria-hidden>+</span></button></h2><section id={`${item.id}-answer`} aria-labelledby={`${item.id}-header`} role="region" hidden={!expanded} data-answer><p>{highlight(item.answer)}</p></section></article>})}</div></div><div className={f.still}><h2>Keep exploring.</h2><p>Follow the implementation, or put a scenario through its paces.</p><div className={s.actions}><Link className={s.outlineButton} href="/docs">Read the documentation ↗</Link><Link className={s.outlineButton} href="/scenarios">Open scenarios ↗</Link></div></div></main><RecoveryFooter/></>
}
