"use client"
import Image from "next/image"
import Link from "next/link"
import type { Route } from "next"
import { useEffect,useRef } from "react"
import { gsap } from "./gsap"
import { LandingNav } from "./landing-nav"
import s from "./utility-pages.module.css"
export function FlightNotFound(){const root=useRef<HTMLElement>(null);useEffect(()=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion:no-preference)',()=>{const el=root.current!,plane=el.querySelector<HTMLElement>('[data-lost-plane]')!;gsap.from(el.querySelectorAll('h1 span'),{rotationX:-90,opacity:0,stagger:.08,duration:.22,repeat:4,ease:'power2.out'});gsap.from(el.querySelectorAll('li'),{y:12,opacity:0,stagger:.08,duration:.32,delay:.7});let frame=0,x=0,y=0,targetX=0,targetY=0;const move=(e:PointerEvent)=>{targetX=(e.clientX/innerWidth-.5)*120;targetY=(e.clientY/innerHeight-.5)*80;if(!frame)frame=requestAnimationFrame(draw)};const draw=()=>{const dx=targetX-x;x+=dx*.04;y+=(targetY-y)*.04;plane.style.transform=`translate(${x}px,${y}px) rotate(${-12+dx*.06}deg)`;frame=Math.abs(dx)+Math.abs(targetY-y)>.1?requestAnimationFrame(draw):0};window.addEventListener('pointermove',move);return()=>{window.removeEventListener('pointermove',move);cancelAnimationFrame(frame)}});return()=>mm.revert()},[]);return <><a href="#not-found-content" className={s.skip}>Skip to page</a><LandingNav/><main ref={root} className={s.notFound} id="not-found-content"><svg viewBox="0 0 1440 900" preserveAspectRatio="none" className={s.brokenArc} aria-hidden><path d="M-100 750Q350 750 700 400" fill="none" stroke="var(--recover)" strokeWidth="2"/><path d="M740 365Q1000 100 1500 90" fill="none" stroke="var(--disrupt)" strokeWidth="2" strokeDasharray="8 14"/></svg><div className={s.lostPlane} data-lost-plane aria-hidden><Image src="/images/olus/aircraft-top.png" alt="" fill sizes="60vw"/></div><div className={s.notFoundContent}><h1 aria-label="404 — page not found"><span aria-hidden>4</span><span aria-hidden>0</span><span aria-hidden>4</span></h1><h2>Flight not found.</h2><p>This route isn’t in the schedule. Let’s get you back to a known destination.</p><ul className={s.board}><li className={s.boardHeader}><span>DESTINATION</span><span>STATUS / NEXT STEP</span></li>{[['Home','/','ON TIME'],['Platform','/simulator','BOARDING'],['Documentation','/docs','GATE OPEN'],['FAQ','/faq','SCHEDULED']].map(([label,href,status])=><li key={href}><Link href={href as Route}>{label}<span>{status} ↗</span></Link></li>)}</ul></div><img src="/images/olus/globe-static.svg" alt="" aria-hidden className={s.globeLimb}/></main></>}

